spring:
  application:
    name: http-api-demo
  profiles:
    active: staging

  mvc:
    locale: zh_CN

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

server:
  address: 127.0.0.1
  port: 8080

logging:
  file: /kt/log/http-api-demo/http-api-demo.log
